# Generated by Django 4.0.4 on 2022-06-04 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menuapp', '0002_rename_menutable_mtable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MTable',
            new_name='Table',
        ),
    ]
